#
# Created: 08-FEB-2024
# Version: 1.0

# Log level for console output
consoleLoglevel: WARNING

# Port for the web server
port: 8080

# Enable or disable the Web UI
enableWebUI: True

sensors:
  - TiltYellow:
      # Plugin to use for this sensor
      plugin: TiltSensor 
      # Color of the Tilt hydrometer
      color: Yellow
      # Temperature calibration offset
      tempclbr: 0
      # Gravity calibration offset
      gravclbr: 0
      # Starting gravity for the Tilt
      startgrav: 1.80
      # Time interval for sending data (in seconds)
      sendtime: 10
      
  - TiltBlue:
      # Plugin to use for this sensor
      plugin: TiltSensor 
      # Color of the Tilt hydrometer
      color: Blue
      # Temperature calibration offset
      tempclbr: 0
      # Gravity calibration offset
      gravclbr: 0
      # Starting gravity for the Tilt
      startgrav: 1.30
      # Time interval for sending data (in seconds)
      sendtime: 10

  - AmbientTemp:
      # Dummy sensor for ambient temperature
      plugin: DummySensor 
      # Fake temperature value for testing
      fakeTemp: 60

actors:
  - Cooling:
      # Plugin for cooling system
      plugin: DummyActor
      # Uncomment below lines if using a TPLinkActor with a specific IP address
      #plugin: TPLinkActor
      #ip: 192.168.111.1

  - Heating:
      # Plugin for heating system
      plugin: DummyActor
      # Uncomment below lines if using a TPLinkActor with a specific IP address
      #plugin: TPLinkActor
      #ip: 192.168.111.2

controllers:
  - Fridge:
      # Plugin for controlling fridge temperature using hysteresis logic
      plugin: HysteresisLogic
      logicCoeffs:
        # Overshoot allowed above setpoint
        allowedOvershoot: 0.4
        # Undershoot allowed below setpoint
        allowedUndershoot: 0.4
        # Whether to keep the fridge cold
        keepCold: yes
      # Actor to control the cooling
      actor: Cooling
      # Sensor to monitor ambient temperature
      sensor: AmbientTemp
      # Initial temperature setpoint for the fridge
      initialSetpoint: 55.0 
      # Initial state of the fridge controller
      initialState: on

  - Heater:
      # Plugin for controlling heater temperature using hysteresis logic
      plugin: HysteresisLogic
      logicCoeffs:
        # Overshoot allowed above setpoint
        allowedOvershoot: 0.4
        # Undershoot allowed below setpoint
        allowedUndershoot: 0.4
        # Whether to keep the heater hot
        keepHot: yes
      # Actor to control the cooling
      actor: Heating
      # Sensor to monitor ambient temperature
      sensor: AmbientTemp
      # Initial temperature setpoint for the heater
      initialSetpoint: 50.0 
      # Initial state of the heater controller
      initialState: off

extensions:
  - web:
      # Web interface plugin
      plugin: SimpleWebView
      endpoints:
        - enable
        - setpoint

connections:
  # Connect the web interface enable switch to the kettle controller state
  - web.enable=>KettleController.state
  
  # Monitor heater power from the web interface
  - Heater.power=>web.heaterpower
  
  # Monitor recirculation temperature from the web interface
  - RecircTemp.temperature=>web.recirtemp
  
  # Set the setpoint from the web interface and reflect it on the kettle controller
  - web.setpoint=>KettleController.setpoint
  - KettleController.setpoint=>web.setpoint
  
  # Control pump state from the web interface
  - web.pump=>Pump.state

