# Clean Testing Config using:
#  tilt-sim
#  tplink-smartplug-simulator
#  blynk.cloud
#
# Created: 08-FEB-2024
# Version: 1.0

consoleLoglevel: WARNING
port: 8080
enableWebUI: True

sensors:
  - TiltOrange:
     plugin: TiltSensor 
     color: Orange
     tempclbr: 0
     gravclbr: 0
     startgrav: 1.050

actors:
  - Cooling:
     plugin: TPLinkActor
     ip: 192.168.254.12

controllers:
  - Fridge:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.4
        allowedUndershoot: 0.4
        keepCold: yes
      actor: Cooling
      sensor: TiltOrange
      initialSetpoint: 30.0 
      initialState: on

extensions:
  - web:
      plugin: SimpleWebView
      endpoints:
        - enable
        - setpoint
        - pump
          #  - blynk:
          #      plugin: Blynk
          #      token: vRlSNd6zTg2XxD7PQ-YCcApIeeo-tnTu

connections:
  #  - TiltOrange.temperature=>blynk.v1
  #  - TiltOrange.gravity=>blynk.v2
  #  - Cooling.power=>blynk.v6
  #  - Heater.power=>blynk.v7
  #  - Fridge.initialSetpoint=>blynk.v8
  #  - blynk.v8=>Fridge.setpoint
  - FermentationHeat.state=>web.enable
  - web.enable=>FermentationHeat.state
