consoleLoglevel: WARNING
logLevel: INFO

port: 8080
enableWebUI: True

sensors:
  - Onewire:
      plugin: W1Sensor
      id: 28-0300a279cd1d
      pollInterval: 30
      sendtime: 10

  - Tilt:
      plugin: TiltSensor
      color: Black
      tempclbr: 0
      gravclbr: 0
      startgrav: 1.0633
      sendtime: 10

actors:
  - Cooling:
      #plugin: DummyActor
      plugin: TPLinkActor
      ip: 192.168.254.10

  - Heating:
      #plugin: DummyActor
      plugin: TPLinkActor
      ip: 192.168.254.11

controllers:
  - Fridge:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.4
        allowedUndershoot: 0.4
        keepCold: yes
      actor: Cooling
      sensor: Tilt
      initialSetpoint: 65.0 
      initialState: on

  - Heater:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.4
        allowedUndershoot: 0.4
        keepHot: yes
      actor: Heating
      sensor: Tilt
      initialSetpoint: 64.0 
      initialState: on

